version: "3.9"
services:

  postgres_pioneer:
    container_name: postgres_pioneer
    image: postgres:14.4
    environment:
      POSTGRES_DB: "pioneer"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pushqa"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres1:/docker-entrypoint-initdb.d
      - postgres1:/var/lib/postgresql/data
    command:
      - -p 5440
    ports:
      - "5440:5440"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d pushqa" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: on-failure

volumes:
  postgres1: