server:
  port: 8060

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5440/pioneer
    username: postgres
    password: pushqa

  flyway:
    enabled: true
    locations: classpath:/db/migration
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    create-schemas: true

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: false

springdoc:
  api-docs:
    path: /api-docs
